-- Core schema for Power Fitness (ported from the "site sport" MySQL DB).
-- ex-MySQL ENUM -> varchar + CHECK. tinyint(1) -> boolean. JSON -> jsonb.
-- Every table: bigint identity PK + created_at/updated_at (BaseEntity) + set_updated_at() trigger (V1).

-- ============================ users / auth ============================
CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(150) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(10)  NOT NULL DEFAULT 'USER' CHECK (role IN ('USER','COACH','ADMIN')),
    avatar      VARCHAR(255),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_users_updated BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  VARCHAR(255) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked     BOOLEAN NOT NULL DEFAULT false,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_refresh_user ON refresh_tokens(user_id);
CREATE TRIGGER trg_refresh_updated BEFORE UPDATE ON refresh_tokens FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================ coach requests (contact form) ============================
CREATE TABLE coach_requests (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(150) NOT NULL,
    phone       VARCHAR(20)  NOT NULL,
    experience  VARCHAR(15)  NOT NULL DEFAULT 'beginner' CHECK (experience IN ('beginner','intermediate','advanced')),
    goals       TEXT NOT NULL,
    status      VARCHAR(12)  NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','contacted','completed')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_coach_requests_updated BEFORE UPDATE ON coach_requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================ assessments ============================
-- Scalar columns = what the analyzer / generator / dashboard read directly.
-- responses jsonb = the long tail (measurements, equipment[], injuries[], strength{}, prefs, allergies...).
CREATE TABLE assessments (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    version               INT NOT NULL DEFAULT 1,
    is_latest             BOOLEAN NOT NULL DEFAULT true,
    date_of_birth         DATE,
    age                   INT NOT NULL,
    gender                VARCHAR(10) CHECK (gender IN ('male','female','other')),
    sex_at_birth          VARCHAR(6)  CHECK (sex_at_birth IN ('male','female')),
    height_cm             NUMERIC(5,2) NOT NULL,
    weight_kg             NUMERIC(5,2) NOT NULL,
    target_weight_kg      NUMERIC(5,2) NOT NULL,
    target_date           DATE,
    workout_frequency     INT NOT NULL DEFAULT 3,
    session_duration_min  INT NOT NULL DEFAULT 60,
    workout_location      VARCHAR(12) NOT NULL DEFAULT 'gym' CHECK (workout_location IN ('gym','home','calisthenics','outdoor')),
    experience_level      VARCHAR(12) NOT NULL DEFAULT 'beginner' CHECK (experience_level IN ('beginner','intermediate','advanced')),
    years_training        NUMERIC(4,1),
    activity_level        VARCHAR(12) NOT NULL DEFAULT 'moderate' CHECK (activity_level IN ('sedentary','light','moderate','very_active')),
    daily_steps           INT,
    occupation_type       VARCHAR(10) NOT NULL DEFAULT 'desk' CHECK (occupation_type IN ('desk','on_feet','physical','shift')),
    primary_goal          VARCHAR(24) NOT NULL CHECK (primary_goal IN ('fat_loss','muscle_gain','weight_gain','athletic_performance','general_fitness')),
    secondary_goal        VARCHAR(50),
    focus_areas           VARCHAR(255) DEFAULT 'full_body',
    meals_per_day         INT NOT NULL DEFAULT 3,
    diet_preference       VARCHAR(16) NOT NULL DEFAULT 'high_protein' CHECK (diet_preference IN ('balanced','high_protein','vegetarian','vegan','keto','mediterranean')),
    water_intake_liters   NUMERIC(3,1) DEFAULT 2.5,
    cooking_ability       VARCHAR(10) CHECK (cooking_ability IN ('none','basic','confident')),
    eating_out_per_week   INT,
    budget_level          VARCHAR(10) CHECK (budget_level IN ('tight','moderate','flexible')),
    caffeine_mg           INT,
    alcohol_units_week    INT,
    sleep_hours           INT DEFAULT 7,
    sleep_quality         INT,
    wake_feeling          VARCHAR(8) CHECK (wake_feeling IN ('groggy','ok','fresh')),
    stress_level          INT,
    energy_level          INT,
    has_injuries          BOOLEAN NOT NULL DEFAULT false,
    is_pregnant           BOOLEAN NOT NULL DEFAULT false,
    medical_conditions    TEXT,
    medications           TEXT,
    medical_ack           BOOLEAN NOT NULL DEFAULT false,
    training_style_pref   VARCHAR(14) CHECK (training_style_pref IN ('strength','bodybuilding','athletic','minimal')),
    coaching_tone_pref    VARCHAR(8)  CHECK (coaching_tone_pref IN ('gentle','direct','tough')),
    checkin_frequency     VARCHAR(10) CHECK (checkin_frequency IN ('weekly','biweekly','monthly')),
    contact_channel       VARCHAR(10) CHECK (contact_channel IN ('email','whatsapp','in_app')),
    units                 VARCHAR(8) NOT NULL DEFAULT 'metric' CHECK (units IN ('metric','imperial')),
    country               VARCHAR(80),
    timezone              VARCHAR(64),
    motivation            TEXT,
    success_definition    TEXT,
    responses             JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_assessments_user_latest ON assessments(user_id, is_latest);
CREATE TRIGGER trg_assessments_updated BEFORE UPDATE ON assessments FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================ assessment analyses ============================
CREATE TABLE assessment_analyses (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id            BIGINT NOT NULL REFERENCES assessments(id) ON DELETE CASCADE,
    user_id                  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bmi                      NUMERIC(4,1) NOT NULL,
    bmi_category             VARCHAR(50) NOT NULL,
    bmr                      INT NOT NULL,
    tdee                     INT NOT NULL,
    target_calories          INT NOT NULL,
    protein_g                INT NOT NULL,
    carbs_g                  INT NOT NULL,
    fats_g                   INT NOT NULL,
    bodyfat_band             VARCHAR(30),
    goal_feasibility         VARCHAR(14) NOT NULL DEFAULT 'REALISTIC' CHECK (goal_feasibility IN ('REALISTIC','AGGRESSIVE','UNREALISTIC','MAINTENANCE')),
    weekly_rate_pct          NUMERIC(4,2),
    projected_weeks          INT,
    risk_count               INT NOT NULL DEFAULT 0,
    data_quality_flag_count  INT NOT NULL DEFAULT 0,
    analysis                 JSONB NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_analyses_assessment ON assessment_analyses(assessment_id);
CREATE TRIGGER trg_analyses_updated BEFORE UPDATE ON assessment_analyses FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================ programs (state machine header) ============================
CREATE TABLE programs (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    coach_id           BIGINT REFERENCES users(id) ON DELETE SET NULL,
    assessment_id      BIGINT REFERENCES assessments(id) ON DELETE SET NULL,
    analysis_id        BIGINT REFERENCES assessment_analyses(id) ON DELETE SET NULL,
    primary_goal       VARCHAR(24) NOT NULL DEFAULT 'general_fitness',
    status             VARCHAR(20) NOT NULL DEFAULT 'DRAFT'
                       CHECK (status IN ('DRAFT','IN_REVIEW','CHANGES_REQUESTED','APPROVED','ACTIVE','SUPERSEDED','COMPLETED','ARCHIVED')),
    active_version_id  BIGINT,
    start_date         DATE,
    target_end_date    DATE,
    next_checkin_date  DATE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_programs_user_status ON programs(user_id, status);
CREATE TRIGGER trg_programs_updated BEFORE UPDATE ON programs FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================ program versions (immutable once approved) ============================
CREATE TABLE program_versions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id           BIGINT NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
    version_no           INT NOT NULL DEFAULT 1,
    status               VARCHAR(20) NOT NULL DEFAULT 'DRAFT'
                         CHECK (status IN ('DRAFT','IN_REVIEW','CHANGES_REQUESTED','APPROVED','ACTIVE','SUPERSEDED','COMPLETED','ARCHIVED')),
    created_by           VARCHAR(10) NOT NULL DEFAULT 'GENERATOR' CHECK (created_by IN ('GENERATOR','COACH','CLIENT')),
    based_on_version_id  BIGINT REFERENCES program_versions(id) ON DELETE SET NULL,
    generator_snapshot   JSONB,
    content              JSONB NOT NULL,
    coach_note           TEXT,
    focus_note           TEXT,
    approved_by          BIGINT REFERENCES users(id) ON DELETE SET NULL,
    approved_at          TIMESTAMPTZ,
    activated_at         TIMESTAMPTZ,
    changelog            JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (program_id, version_no)
);
CREATE INDEX idx_pv_program ON program_versions(program_id, version_no);
CREATE TRIGGER trg_pv_updated BEFORE UPDATE ON program_versions FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE programs ADD CONSTRAINT fk_programs_active_version
    FOREIGN KEY (active_version_id) REFERENCES program_versions(id) ON DELETE SET NULL;

-- ============================ review events / change requests ============================
CREATE TABLE program_review_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id  BIGINT NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
    version_id  BIGINT REFERENCES program_versions(id) ON DELETE SET NULL,
    actor_id    BIGINT REFERENCES users(id) ON DELETE SET NULL,
    actor_role  VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
    action      VARCHAR(24) NOT NULL
                CHECK (action IN ('SUBMITTED','EDITED','APPROVED','CHANGES_REQUESTED','RESUBMITTED','REACTIVATED','SUPERSEDED','COMPLETED','ARCHIVED','NEW_VERSION','MIGRATED')),
    payload     JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_pre_program ON program_review_events(program_id, created_at);
CREATE TRIGGER trg_pre_updated BEFORE UPDATE ON program_review_events FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE program_change_requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id   BIGINT NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
    version_id   BIGINT REFERENCES program_versions(id) ON DELETE SET NULL,
    fields       JSONB NOT NULL,
    note         TEXT,
    resolved     BOOLEAN NOT NULL DEFAULT false,
    resolved_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_pcr_program ON program_change_requests(program_id, resolved);
CREATE TRIGGER trg_pcr_updated BEFORE UPDATE ON program_change_requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================ roadmaps (mirror table read by dashboards) ============================
CREATE TABLE roadmaps (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    assessment_id       BIGINT REFERENCES assessments(id) ON DELETE SET NULL,
    analysis_id         BIGINT REFERENCES assessment_analyses(id) ON DELETE SET NULL,
    program_version_id  BIGINT REFERENCES program_versions(id) ON DELETE SET NULL,
    bmi                 NUMERIC(4,1) NOT NULL,
    bmi_category        VARCHAR(50) NOT NULL,
    bmr                 INT NOT NULL,
    tdee                INT NOT NULL,
    target_calories     INT NOT NULL,
    protein_g           INT NOT NULL,
    carbs_g             INT NOT NULL,
    fats_g              INT NOT NULL,
    water_liters        NUMERIC(3,1) NOT NULL,
    roadmap_title       VARCHAR(150) NOT NULL,
    roadmap_data        JSONB NOT NULL,
    status              VARCHAR(10) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','ARCHIVED','COMPLETED')),
    coach_status        VARCHAR(16) NOT NULL DEFAULT 'PENDING_REVIEW' CHECK (coach_status IN ('PENDING_REVIEW','APPROVED','REJECTED','NEEDS_REVISION')),
    coach_id            BIGINT REFERENCES users(id) ON DELETE SET NULL,
    coach_notes         TEXT,
    reviewed_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_roadmaps_user ON roadmaps(user_id, status, coach_status);
CREATE TRIGGER trg_roadmaps_updated BEFORE UPDATE ON roadmaps FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================ tracking ============================
CREATE TABLE habit_logs (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    log_date             DATE NOT NULL,
    water_completed      BOOLEAN NOT NULL DEFAULT false,
    workout_completed    BOOLEAN NOT NULL DEFAULT false,
    nutrition_completed  BOOLEAN NOT NULL DEFAULT false,
    sleep_completed      BOOLEAN NOT NULL DEFAULT false,
    sleep_hours          INT NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, log_date)
);
CREATE TRIGGER trg_habit_logs_updated BEFORE UPDATE ON habit_logs FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE progress_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    logged_on   DATE NOT NULL,
    weight_kg   NUMERIC(5,2),
    waist_cm    NUMERIC(5,2),
    hip_cm      NUMERIC(5,2),
    chest_cm    NUMERIC(5,2),
    arm_cm      NUMERIC(5,2),
    thigh_cm    NUMERIC(5,2),
    neck_cm     NUMERIC(5,2),
    energy      INT,
    note        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, logged_on)
);
CREATE TRIGGER trg_progress_logs_updated BEFORE UPDATE ON progress_logs FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE workout_sessions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    program_version_id  BIGINT REFERENCES program_versions(id) ON DELETE SET NULL,
    day_index           INT,
    day_label           VARCHAR(120),
    session_date        DATE NOT NULL,
    duration_min        INT,
    rpe                 INT,
    note                TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_ws_user_date ON workout_sessions(user_id, session_date);
CREATE TRIGGER trg_ws_updated BEFORE UPDATE ON workout_sessions FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================ notifications ============================
CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type        VARCHAR(50) NOT NULL,
    title       VARCHAR(160) NOT NULL,
    body        TEXT,
    link        VARCHAR(255),
    read_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_notifications_user ON notifications(user_id, read_at);
CREATE TRIGGER trg_notifications_updated BEFORE UPDATE ON notifications FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================ exercise library ============================
CREATE TABLE exercises (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(120) NOT NULL UNIQUE,
    category       VARCHAR(12) NOT NULL DEFAULT 'FULL_BODY' CHECK (category IN ('PUSH','PULL','LEGS','CORE','FULL_BODY','CARDIO')),
    primary_muscle VARCHAR(40),
    equipment      VARCHAR(40) NOT NULL DEFAULT 'bodyweight',
    patterns       VARCHAR(255),
    is_compound    BOOLEAN NOT NULL DEFAULT false,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_exercises_updated BEFORE UPDATE ON exercises FOR EACH ROW EXECUTE FUNCTION set_updated_at();
