-- Reference data: the exercise library (from the original migrate_programs.php seed).
INSERT INTO exercises (name, category, primary_muscle, equipment, patterns, is_compound) VALUES
('Barbell Back Squat','LEGS','quads','barbell','squat,knee,lower_back',true),
('Front Squat','LEGS','quads','barbell','squat,knee',true),
('Goblet Squat','LEGS','quads','dumbbell','squat,knee',true),
('Leg Press','LEGS','quads','machine','knee',true),
('Bulgarian Split Squat','LEGS','quads','dumbbell','knee',true),
('Walking Lunge','LEGS','quads','dumbbell','knee',true),
('Romanian Deadlift','LEGS','hamstrings','barbell','deadlift,hip,lower_back',true),
('Conventional Deadlift','PULL','back','barbell','deadlift,lower_back,hip',true),
('Hip Thrust','LEGS','glutes','barbell','hip',true),
('Glute Bridge','LEGS','glutes','bodyweight','hip',false),
('Lying Leg Curl','LEGS','hamstrings','machine','',false),
('Leg Extension','LEGS','quads','machine','knee',false),
('Standing Calf Raise','LEGS','calves','machine','ankle',false),
('Barbell Bench Press','PUSH','chest','barbell','bench,shoulder',true),
('Incline Dumbbell Press','PUSH','chest','dumbbell','shoulder',true),
('Machine Chest Press','PUSH','chest','machine','',true),
('Push-up','PUSH','chest','bodyweight','',true),
('Weighted Dip','PUSH','chest','bodyweight','dip,shoulder,elbow',true),
('Overhead Barbell Press','PUSH','shoulders','barbell','overhead press,shoulder',true),
('Seated Dumbbell Shoulder Press','PUSH','shoulders','dumbbell','shoulder',true),
('Landmine Press','PUSH','shoulders','barbell','',true),
('Cable Lateral Raise','PUSH','shoulders','cable','',false),
('Dumbbell Lateral Raise','PUSH','shoulders','dumbbell','',false),
('Rope Tricep Pushdown','PUSH','triceps','cable','',false),
('Overhead Tricep Extension','PUSH','triceps','dumbbell','elbow',false),
('Skullcrusher','PUSH','triceps','barbell','skullcrusher,elbow',false),
('Pull-up','PULL','back','bodyweight','',true),
('Lat Pulldown','PULL','back','machine','',true),
('Chest-Supported Row','PULL','back','machine','',true),
('Barbell Bent-Over Row','PULL','back','barbell','bent-over,lower_back',true),
('Single-Arm Dumbbell Row','PULL','back','dumbbell','',true),
('Seated Cable Row','PULL','back','cable','',true),
('Face Pull','PULL','rear delts','cable','',false),
('Incline Dumbbell Curl','PULL','biceps','dumbbell','',false),
('Hammer Curl','PULL','biceps','dumbbell','',false),
('Barbell Curl','PULL','biceps','barbell','wrist',false),
('Hanging Leg Raise','CORE','abs','bodyweight','',false),
('Cable Woodchopper','CORE','obliques','cable','',false),
('Plank','CORE','abs','bodyweight','',false),
('Ab Wheel Rollout','CORE','abs','bodyweight','lower_back',false),
('Back Extension','CORE','lower back','bodyweight','',false),
('Band Pull-Apart','PULL','rear delts','bands','',false),
('Band Chest Press','PUSH','chest','bands','',true),
('Band Row','PULL','back','bands','',true),
('Cycling Intervals','CARDIO','conditioning','machine','',false),
('Rowing Intervals','CARDIO','conditioning','machine','lower_back',false),
('Incline Walk','CARDIO','conditioning','machine','',false)
ON CONFLICT (name) DO NOTHING;
