-- Shop: outfits/supplements/accessories/equipment, cash-on-delivery orders only (no payment gateway).

CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(160) NOT NULL,
    category    VARCHAR(20) NOT NULL CHECK (category IN ('SUPPLEMENTS','APPAREL','ACCESSORIES','EQUIPMENT')),
    description TEXT,
    price       NUMERIC(10,3) NOT NULL CHECK (price > 0),
    image_url   VARCHAR(500),
    stock_qty   INT NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
    active      BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_products_category_active ON products(category, active);
CREATE TRIGGER trg_products_updated BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE shop_orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                    CHECK (status IN ('PENDING','CONFIRMED','SHIPPED','DELIVERED','CANCELLED')),
    subtotal        NUMERIC(10,3) NOT NULL,
    delivery_fee    NUMERIC(10,3) NOT NULL DEFAULT 0,
    total           NUMERIC(10,3) NOT NULL,
    recipient_name  VARCHAR(120) NOT NULL,
    phone           VARCHAR(30) NOT NULL,
    address_line    VARCHAR(255) NOT NULL,
    city            VARCHAR(100) NOT NULL,
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_shop_orders_user ON shop_orders(user_id, created_at);
CREATE INDEX idx_shop_orders_status ON shop_orders(status, created_at);
CREATE TRIGGER trg_shop_orders_updated BEFORE UPDATE ON shop_orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE shop_order_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT NOT NULL REFERENCES shop_orders(id) ON DELETE CASCADE,
    product_id    BIGINT REFERENCES products(id) ON DELETE SET NULL,
    product_name  VARCHAR(160) NOT NULL,
    unit_price    NUMERIC(10,3) NOT NULL,
    quantity      INT NOT NULL CHECK (quantity > 0),
    size          VARCHAR(10),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_shop_order_items_order ON shop_order_items(order_id);
CREATE TRIGGER trg_shop_order_items_updated BEFORE UPDATE ON shop_order_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();
